### PR TITLE
Fix clippy lints; return errors rather than panic

### LINKED ISSUE #114: Clippy warnings
Derived code is triggering Clippy warnings, more specifically:

* clippy::indexing_slicing,
* clippy::panic_in_result_fn,
* clippy::str_to_string,
* clippy::unreachable,
* clippy::unwrap_in_result

Please consider using `#[automatically_derived]`/`#[allow(clippy::SOME_LINT]` or audit the codebase.

### PR DESCRIPTION
**Pull request by erickt**
This cleans up clippy lints, both in the library itself, and in the
generated code. As part of this change, it changes a few locations where
we would have panicked on values passed in by the user to instead return
an error.

However, I left one place that unwraps in the generated code. After we have
parsed all the arguments, we check that all of the required arguments. If
not, we return an error. It's unfortunately a little difficult to prove
to rust that we've handled all the arguments. I left the unwrap()s in place
in case there's a logic error we have in handling this, and annotated the
code with `#[allow(clippy::unwrap_in_result)]` to allow for this case.

Closes #114

### CODE REVIEW

File: argh_derive/src/lib.rs [hunk 1]
```diff
@@ -471,7 +467,11 @@ fn impl_from_args_struct_redact_arg_values<'a>(
             #missing_requirements_ident.err_on_any()?;
 
             let mut __redacted = vec![
-                #cmd_name,
+                if let Some(cmd_name) = __cmd_name.last() {
```
Comment (richkadel) [inline argh_derive/src/lib.rs:470]: This change looks non-trival. 

Not a blocker, but I'm curious why?

Seems like a lot of extra effort, hard to really understand what it's doing, and I'm not sure what the real benefit is of generating an Err(EarlyExit()) instead of what it was doing before.

**Review by richkadel — APPROVED** [review]

File: argh_derive/src/lib.rs (hunk 1 above)
Comment (erickt) [reply argh_derive/src/lib.rs:470]: In this case, we'd panic if someone had:

```
#[derive(FromArgs)]
#[argh(subcommand)]
struct Foo { ... }
Foo::redact_arg_values(&[], &[...]); // panics
```

This changes the code to instead return an error, because the user needs to be passing in the subcommand name in order to generate the help string.

The other option we could just not prepend the cmd name to the redacted list, but since this is part of the semantics of subcommands, I figure we should error in that case.

Comment (richkadel) [reply argh_derive/src/lib.rs:470]: Got it! Thanks!
